name: securesphere
description: A decentralized, privacy-focused password manager with seed phrase authentication.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^3.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0
  bip39: ^1.0.6
  encrypt: ^5.0.1
  local_auth: ^2.1.5
  get: ^4.6.5
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  crypto: ^3.0.3
  http: ^1.1.0
  app_links: ^3.4.3
  url_launcher: ^6.1.12
  

  cupertino_icons: ^1.0.2
  bip32: ^2.0.0
  hex: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.4.6
  dart_code_metrics: 4.19.2

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/